spring:
  datasource:
    url: jdbc:mariadb://database-shop.czv6z9c7kqi9.ap-northeast-2.rds.amazonaws.com:3306/helloshop
    username: admin
    password: springboot!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  rabbitmq:
    host: 3.36.203.222
    username: hello-shop
    password: hello-shop

decorator:
  datasource:
    p6spy:
      enable-logging: false

app:
  amqp:
    queueName: shop2delivery.queue
    exchangeName: shop2delivery.direct
    routingKey: delivery-delegate

cloud:
  aws:
    s3:
      bucket: jeju-bucket
      dirName: images
