spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/helloshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: 192.168.35.199
    username: hello-shop
    password: hello-shop

logging:
  level:
    org.hibernate.SQL: debug # 로거를 통해 출력
    com.amazonaws.util.EC2MetadataUtils: error

app:
  amqp:
    queue-name: shop2delivery.queue
    exchange-name: shop2delivery.direct
    routing-key: delivery-delegate

  image:
    upload_path: C:\Users\user\image_factory
    download_url: http://localhost:8081/images/download

  iam-port:
    imp_key: '0961094963459268'
    imp_secret: 'D7dRYbk3a1fgVGfyZG7YVNN8FhEjevSSC6JBh3Er4UH0AXyAEGzzunI9EmtSSlKvru6JyKbCESDfQcQu'