server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://database-shop.czv6z9c7kqi9.ap-northeast-2.rds.amazonaws.com:3306/helloshop
    username: admin
    password: springboot!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true

    properties:
        default_batch_fetch_size: 100 # IN쿼리 개수

  rabbitmq:
    host: 3.36.203.222
    username: hello-shop
    password: hello-shop
