server:
  port: 8081

spring:
  jpa:
    properties:
      default_batch_fetch_size: 100

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true

app:
  iam-port:
    imp_key: '0961094963459268'
    imp_secret: 'D7dRYbk3a1fgVGfyZG7YVNN8FhEjevSSC6JBh3Er4UH0AXyAEGzzunI9EmtSSlKvru6JyKbCESDfQcQu'
