server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/helloshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # IN 쿼리의 개수

logging:
  level:
    org.hibernate.SQL: debug # 로거를 통해 출력

app:
  image:
    upload_path: C:\Users\user\image_factory
    download_url: http://localhost:8081/images/download

  iam-port:
    imp_key: '0961094963459268'
    imp_secret: 'D7dRYbk3a1fgVGfyZG7YVNN8FhEjevSSC6JBh3Er4UH0AXyAEGzzunI9EmtSSlKvru6JyKbCESDfQcQu'
